export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Admin} from './Admin/Admin'
export {default as Blogs} from './Blogs/Blogs'
export {default as Contact} from './Contact/Contact'
export {default as Trainings} from './Trainings/Trainings'
export {default as Dashboard} from './Dashboard/Dashboard';
export {default as Training} from './Training/Training'
export {default as Post} from './Post/Post'